### ISSUE TITLE
点数手牌が固定、特殊な役満から実装してみようの巻。

### ISSUE THREAD

**Issue by bobkuro** [jtwp470/gochiusa-bot#10]
条件も決まってるし、まだわかりやすいのでは

余談：清一色の方がシンプルって節もあるけど……全ての牌にsou(,pin,man)の文字列を含むって条件文にすればどうだろう

**Comment by ryosan-470** [comment]
この場合,特殊な役か通常の役かでランダム選択にするって感じですかね?
つまり特殊な役は場合によっては4つの面子と雀頭という形にあてはまらないからもう埋め込んでおくてきな?

**Comment by bobkuro** [comment]
国士無双(と七対子)はくっそ特殊だから埋め込みでいいと思う。
ソレ以外は、
役満判別フィルター
trueだったら終了
falseだったら清一色判別フィルター(そして以後の役判定機)へ
って感じで作ってみては？って感じ。
九蓮宝燈、大車輪、緑一色があるので、先に役満フィルターがいいかなーってかんじ

**Comment by ryosan-470** [comment]
わからん.専門用語全くわからんorz

**Comment by bobkuro** [comment]
ランダム生成された面子で役を判定して、点数までわかるといいよねって言うのが僕の希望で。

![chin-iso](https://cloud.githubusercontent.com/assets/10018026/8173129/28148382-1404-11e5-9644-599393bc5041.gif)
これが清一色じゃん？これは保有してる牌が"-sou" or "-man" or "-pin"のいずれかのみで構成されてるやん？これって条件として実装しやすそうだからいいなっておもったんだわ。そこで、下の役を見て欲しいのだけど

![churen](https://cloud.githubusercontent.com/assets/10018026/8173130/281ce9aa-1404-11e5-8b8a-cb7bf206d8e5.gif)
![ryuiso](https://cloud.githubusercontent.com/assets/10018026/8173132/281ebcb2-1404-11e5-8135-b80904b99f5b.gif)
![daisharin](https://cloud.githubusercontent.com/assets/10018026/8173131/281e8328-1404-11e5-8cc8-5f4c25de99f6.gif)
これらは役満だけど、清一色と同じような構成牌になるやん？(「緑一色に發をいれなくてはならない」なら緑一色は混一色との差別化ってところになるけど。)
![unknown](https://cloud.githubusercontent.com/assets/10018026/8173225/31922a94-1405-11e5-8841-706ff20973a8.png)

となると、役満に清一色の役数がのらないのは自明だから、役満かどうかを先に判定して、trueならそこで点数だしちゃううし、falseならそこから、清一色、その他の役を判定してから点数計算していく流れにすればいけるんじゃないかなって。

**Comment by jtwp470** [comment]
Please do pull request to implement the code of your idea!

**Comment by ryosan-470** [comment]
さすがに点数計算まで実装するのは重すぎるので先にランダム生成する方におもきを置きましょう!!

もしどうしてもというのであればCoffeeScriptを学んで実装してPRください. :bow:

**Comment by bobkuro** [comment]
wei

**Comment by ytmt365** [comment]
先ほど言った話

``` coffee
shunts = [
":1man: :2man: :3man:", ":2man: :3man: :4man:" , ... , ":7man: :8man: :9man:",
":1pin: :2pin: :3pin:", ... ]

kots = [
":1pin: :1pin: :1pin:", ... ]
```

という感じで順子・刻子(・槓子)を作り，それをランダムで4つ引っ張ってくる

**Comment by ryosan-470** [comment]
その場合例えばこういう感じのものが生まれてくる可能性がありませんか?

```
:1man: :1man: :1man: :1man: :2man: :3man: :1man: :2man: :3man: ....
```

こういうのを弾くパターンを考えなきゃいけない気がします.

**Comment by ytmt365** [comment]
こうかなぁ(記法は曖昧)

``` coffee
tehai = [
"shunts1 shunts2 shunts3 shunts4 head", "shunts1 shunts2 shunts3 kots1 head",
"shunts1 shunts2 kots1 kots2 head", "shunts1 kots1 kots2 kots3 head", "kots1 kots2 kots3 kots4 head"]

shunts1 = msg.random shunts
shunts2 = msg.random shunts
...
```

ちょっとまだCoffeeScript理解してないんであとでやります

**Comment by ryosan-470** [comment]
@ksepynoin そういう書き方してそもそもCoffeeScriptのビルド通りますか?

**Comment by bobkuro** [comment]
(それとそれって稀に全く同じshuntsが3つ並んだら三暗刻、4つなら三槓子になるんで考慮の必要ありなのです)
