### ISSUE TITLE
How to contribute this repository

### ISSUE THREAD

**Issue by ryosan-470** [jtwp470/gochiusa-bot#12]
# The guide of Pull Request for gochiusa-bot
1. Forkしましょう.Forkは右上のStarの横にあります.
2. 機能を書き書きします.このとき気をつけて欲しいのは,
   - 他のプルリクエストを見て重複はないかを確認します.重複がある場合は基本的にPRしても受理されないと思いましょう.
   - **ブランチを切りましょう.**
   - テストやビルドは最低限通るようにしましょう.
   - コミットログにIssue番号を混ぜてください. (混ぜ方: `hogeを追加 Issue: #12`)
3. Pull Requestを投げます.このとき
   - コミットログはなるべく1つにまとめてください.(`git rebase`でできる) (無理してしなくてもよい)
   - **masterブランチには投げないこと**!

この辺に気をつければ多分問題ないでしょう.

このIssueでは開発にあたってわからないことや質問をかいてください.

**Comment by index30** [comment]
isuue 番号は#12で良い？

**Comment by ryosan-470** [comment]
えーとどの機能に対してPRを送ってくれるんでしょうか?
例えば #11 に対しての機能としてPRを送るときは コミットログ文末に `#11`をつけてくれるといいなってことです.

**Comment by index30** [comment]
なるほど、了解です

**Comment by ryosan-470** [comment]
Go to [wiki](https://github.com/jtwp470/gochiusa-bot/wiki)
