### ISSUE TITLE
チートイツ表示の時に現れる , (コンマ)について

### ISSUE THREAD

**Issue by bobkuro** [jtwp470/gochiusa-bot#22]
画像の見たまんまで、七対子の手牌のなかに , が入る件についてのことなのでよろしくお願いします
![2015-06-19 09 26 41](https://cloud.githubusercontent.com/assets/10018026/8245160/60a5f2fe-1665-11e5-844c-54b5d4dac2c1.png)
![2015-06-19 09 26 25](https://cloud.githubusercontent.com/assets/10018026/8245161/60a6b0b8-1665-11e5-8c13-011562cc7551.png)

**Comment by index30** [comment]
まあこれはコードが長くなるから(めんどいから)後回しにしてるだけでやろうと思えばすぐなおせる(屑)

**Comment by bobkuro** [comment]
90％できてますっていいたくなりますよね(med教授)

**Comment by index30** [comment]
まあ5枚問題解決してからってことで
