### ISSUE TITLE
折部やすなー

### ISSUE THREAD

**Issue by ryosan-470** [jtwp470/gochiusa-bot#30]
![](http://livedoor.blogimg.jp/nemusoku/imgs/9/a/9a7f6a3a.jpg)

文字の部分を任意の文字を入れて吐くものがほしいなぁ

**Comment by ryosan-470** [comment]
Nodejsでコマンドラインを実行する.
https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=node%20js%20exec%20command

**Comment by ryosan-470** [comment]
Herokuでcanvasを利用しようとするとコンパイルエラーになって死ぬ.
解決法としてBuildpackを変えた.
https://github.com/mojodna/heroku-buildpack-cairo

ついでに Travis CIも死ぬようになったので後で修正する必要がある.

**Comment by ryosan-470** [comment]
@sga0221  やってほしいこと
- [x] コミットをまとめる 2コミットくらい?
  - ついでにコミットメッセージ中に ref #30 とかつけてくれると嬉しい
- [x] `git rebase origin master`  して 今のorigin/master のHEADから伸ばすようにする
- [x] まとめたコミットの上に, READMEの追加

(※: 各部終わったらチェックを付けてくれるとどこまでやったかわかるので嬉しい)

**Comment by ryosan-470** [comment]
### TODO:
- [x] Travis CIが死ぬようになったからそれを治す
- [x] `app.json` の修正 (これしないとデプロイできない)
- [ ] jsファイルの修正
- [ ] Webから同様の機能を呼び出しできるようにする
- [x] 表示を綺麗な感じにする
- [ ] メインにデプロイ

**Comment by sga0221** [comment]
Change buildpacks because canvas compile error
のコミットは残すべきですか

**Comment by ryosan-470** [comment]
@sga0221 まとめて問題無いです. あとpackage.json の buildpacks の場所で `https://github.com/ddollar/heroku-buildpack-multi.git` に書き換えてもらっていいっすか

**Comment by sga0221** [comment]
buildpacksなんて記述見当たらないんだが
