### ISSUE TITLE
麻雀機能の行数削減等

### ISSUE THREAD

**Issue by ytmt365** [jtwp470/gochiusa-bot#34]
Slackの過去ログ保存量をできる限り消費しないようにするため，出力される行数の削減をしたいです．

**Comment by ryosan-470** [comment]
今のままだと最大3回`msg.send`が呼ばれる感じですか?

例えばですが文字列を結合していけばこれは解決できるのではないでしょうか

**Comment by ryosan-470** [comment]
もしプルリクエストを送る場合, これからは`heroku-deploy-test`ブランチにお願いします :octopus:

**Comment by ytmt365** [comment]
現在

1行目: ドラ表示．風
2行目: 手牌
3行目: 追加されるドラ
4行目: 煽りコメント

となっていて最大4行消費します．

**Comment by ytmt365** [comment]
行数削減方法の例として，1行目に手牌以外の情報(すべてのドラ，一発か否か)をすべて集める，というようにすることで2行で出力を済ませられます．その場合，煽りコメントが残らなくなりますが．

**Comment by ryosan-470** [comment]
というより`msg.send`1回で全部済ませられませんか?

例えば`str = ""`があったとして 

``` coffeescript
str = ""
str += dora_view   // ドラ表示牌
str += 手牌            // 手牌
str += 追加ドラ
if 煽りが必要なら
   str += 煽り

msg.send str
```

のような感じにすればいいと思います.

Slackの制限ですがあくまで1回のつぶやき?で1カウントだと思うのでもしかすると改行は関係ないのかもしれませんが少なくとも`msg.send`の回数を1回にするといいと思います.

**Comment by ytmt365** [comment]
`msg.send`を1回だけ使う方向で実装してみます．

**Comment by ryosan-470** [comment]
↑?

**Comment by ytmt365** [comment]
yeah
