### ISSUE TITLE
LaTeX機能でfrac(分数)出力がされないのとスペースに対応する

### ISSUE THREAD

**Issue by ryosan-470** [jtwp470/gochiusa-bot#45]
今ごちうさBOTについているLaTeX出力機能ではfracが使えないらしい.そこで使えるサービスに移行させるのと更にはスペースを追加すると今はきちんと出力できないが正規表現マッチにスペースも追加して対応できるように変更する.

**Comment by ytmt365** [comment]
実験してみた結果なので絶対正しいとは言えませんが，式を

``` latex
$\frac{1}{2}$
```

ではなく

``` latex
\frac{1}{2}
```

のように，`$`記号で囲まずに送ると正しく表示されるみたい．

**Comment by ryosan-470** [comment]
Ref #48 に引き継ぎ
