### ISSUE TITLE
ごちうさ画像を吐くのが害悪と言う意見

### ISSUE THREAD

**Issue by ryosan-470** [jtwp470/gochiusa-bot#7]
ごちうさと言う言葉に反応して画像を返すのはやめて欲しいらしいw

**Comment by ryosan-470** [comment]
気のせいでしょ

**Comment by bobkuro** [comment]
ごちうさってワード出ること少ないしごちうさbotの機嫌みたいなもんでしょ我慢しよう(提案)( ◔ิω◔ิ)

**Comment by ryosan-470** [comment]
たぶんですがこいつ馬鹿なのでgochiusa-botという名前のgochiusaにも反応して画像を返します.なのでケシケシします

**Comment by ryosan-470** [comment]
反応しなくなりました
