### ISSUE TITLE
麻雀の役を吐かせるごちうさらしくない機能

### ISSUE THREAD

**Issue by ryosan-470** [jtwp470/gochiusa-bot#8]
Branches: https://github.com/jtwp470/gochiusa-bot/tree/dev-mahjong :mahjong:

**Comment by ryosan-470** [comment]
#### CoffeeScript 入門的なドキュメント

https://gist.github.com/udzura/0cb2447c305c51670414

#### Hubotを自環境で構築して動かす
- [Hubotで西木野真姫botを作って動かす](http://memo.sanographix.net/post/88371442780)

よくわかっていませんがたぶんnodeとcoffeescriptが入っていれば動くのではないでしょうか?

**Comment by bobkuro** [comment]
３牌ずつのセットを４つ、雀頭１つをランダムに組み合わせる技ってできないの？？順子と刻子を生成する仕事がアレだけど
チートイツ、国士無双は別ルートでつくらないかんくなるけども

**Comment by bobkuro** [comment]
そう言えば国士12牌のテンパイですらないガチション牌を観測しました。

**Comment by ryosan-470** [comment]
なるほどな 調査してみるわ

一応役が全然ないので追加してほしいです

@bobkuro :bow:

**Comment by jtwp470** [comment]
今現在ある手役一覧:
https://github.com/jtwp470/gochiusa-bot/blob/dev-mahjong/scripts/mahjong.coffee#L7L16

**Comment by bobkuro** [comment]
コレは考えついたらコメントで書けば実装してくれる的な？？
ごちうさbotを編集する知識以前にがなに言語なのかわからんし…

**Comment by bobkuro** [comment]
そうそう、ション牌に奴これ
![2015-06-15 10 29 47](https://cloud.githubusercontent.com/assets/10018026/8159648/b2f47c3e-13a3-11e5-85cc-7bd4e082bd79.png)

**Comment by ryosan-470** [comment]
@bobkuro CoffeeScriptでかいてます.(JSでもOK) できたら実装して欲しいけど意見だけでも可.ただ実装者本人(@jtwp470)自体があまり麻雀の役に詳しくないので詳しい人に書いて欲しさ.

**Comment by ryosan-470** [comment]
で結局どうしようかといった感じ

**Comment by index30** [comment]
完全にプルリクエストの仕方忘れたんだけどこれの通りにいけば良い感じかのう
http://kik.xii.jp/archives/179

**Comment by ryosan-470** [comment]
@index30 Refer to #12  or Slack :bow:

**Comment by index30** [comment]
Oh yeah Thank U

**Comment by ryosan-470** [comment]
@index30 GJ!
